name = "Future Battlefield Pack (F.B.P.) Defenses"
uid = "5t3edt-btz6-9438-h6ui-9287zt47fds"
version = 1.0
copyright = "Copyright © 2019, CDRMV (aka CDR Deadalus)"
description = "FAF Version 1.0 'Future Battlefield Pack Defenses' is a Submod for F.B.P. It adds several new Defense Buildings like Outposts, Fortresses and more to the Game."
author = "CDRMV (aka CDR Deadalus)"
url = "http://www.moddb.com/mods/fbp-future-battlefield-pack"
icon = "/mods/Future Battlefield Pack Defenses/Icon.png" 
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
